name: wordpress_api
description: A WordPress REST API client for dart with support for WooCommerce
  and custom namespaces.
version: 0.2.1
homepage: https://github.com/dhmgroup/dart-wp

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  dio: ^3.0.10
  freezed_annotation: ^0.12.0
  logger: ^0.9.4
  meta: ^1.2.3

dev_dependencies:
  build_runner: null
  freezed: ^0.12.1
  json_serializable: ^3.5.0
  lint: ^1.3.0
