name: wordpress_api
description: A WordPress REST API client for dart with support for WooCommerce
  and custom namespaces.
version: 0.3.0
homepage: https://github.com/dhmgroup/dart-wp

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  html: ^0.15.0
  logger: ^1.0.0
  meta: ^1.3.0
